<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="poorvid" failures="1" tests="2" name="Test" time="12.991" errors="0" timestamp="2022-11-29T15:12:56 IST">
  <testcase classname="zephyrsquad.jenkins.secondTest" name="secondtest" time="2.396">
    <failure type="java.lang.AssertionError" message="testcase failed expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: testcase failed expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at zephyrsquad.jenkins.secondTest.secondtest(secondTest.java:38)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- secondtest -->
  <testcase classname="zephyrsquad.jenkins.firstTest" name="firsttest" time="3.045"/>
</testsuite> <!-- Test -->
