<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="poorvid" failures="1" tests="3" name="Test" time="14.945" errors="0" timestamp="2022-12-06T12:32:47 IST">
  <testcase classname="zephyrsquad.jenkins.secondTest" name="secondtest" time="2.179">
    <failure type="java.lang.AssertionError" message="testcase failed expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: testcase failed expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at zephyrsquad.jenkins.secondTest.secondtest(secondTest.java:38)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- secondtest -->
  <testcase classname="zephyrsquad.jenkins.secondTest" name="testing" time="0.0">
    <skipped/>
  </testcase> <!-- testing -->
  <testcase classname="zephyrsquad.jenkins.firstTest" name="firsttest" time="5.627"/>
</testsuite> <!-- Test -->
